[[redirects]]
  from = "/pages/admin*"
  to = "/error/404/404.html"
  status = 404
  
[[redirects]]
  from = "/pages/auth/*"
  to = "/error/auth/auth-404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/error/404/404.html"
  status = 404

